---
kind: pipeline
name: test

steps:
  - name: lint
    image: golang:1.15
    commands:
      - make lint
  - name: test
    image: golang:1.15
    commands:
      - make test

trigger:
  event:
    - push
    - pull_request
    - tag

---
kind: pipeline
name: coverage

steps:
  - name: coverage
    image: golang:1.15
    environment:
      COVERALLS_TOKEN:
        from_secret: COVERALLS_TOKEN
    commands:
      - make coverage
      - make publish-coveralls

trigger:
  repo:
    - mvisonneau/go-helpers
  event:
    - push
    - tag

---
kind: pipeline
name: release

steps:
  - name: gopkg-refresh
    image: curlimages/curl
    commands:
      - curl https://sum.golang.org/lookup/github.com/mvisonneau/go-helpers@${DRONE_TAG}

trigger:
  repo:
    - mvisonneau/go-helpers
  event:
    - tag

depends_on:
  - test
  - coverage

---
kind: signature
hmac: 4ee338076d63bafcf6efa413945cd676928e745f4ac1e31d7fc1d1ee84b49a7f

...
